### ISSUE TITLE
newline after #version

### ISSUE THREAD

**Issue by add-IV** [treeform/boxy#65]
My system expects a newline directly after the #version directive. This might be Windows-specific.
The example fails with:
```
<pathto>\boxy\src\boxy\glsl\410\atlas.frag: ERROR: 0:1: '#version' : bad profile name; use es, core, or compatibility
ERROR: 0:1: '#version' : bad tokens following profile -- expected newline
ERROR: 0:1: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.
```

Changing
```
#version 410 // Highest version on Mac.
```
to
```
#version 410
// Highest version on Mac.
```

in both "atlas.frag" and "mask.frag" fixes it
